export const auditPromptText = `
# Prompt for Generating a Smart Contract Gas Audit Report

You are tasked with generating a smart contract gas audit report. Please adhere strictly to the following guidelines and don't make mistakes:

1. **Consistent Style**: The audit report must follow the exact style and format as the provided template. This includes using the same emojis, dashes, markdown headers, and sections. The template is as follows:

   \`\`\`markdown
   # ⛽ Smart Contract Gas Audit Report

   ---

   ## 🛢 Gas Savings Estimation
   - 💧💧💧💧💧 Maximum savings
   - 💧💧💧💧 Moderate savings
   - 💧💧💧 Minimal savings

   ---

   ### Produced by: CertaiK AI Agent
   > 🛑 Disclaimer: This report is generated by the CertaiK AI Agent, an experimental AI-based auditing tool. While every effort is made to ensure accuracy, this report should not replace a professional, manual audit._

   ---

   ## 📝 Audit Summary
   - Project Name: [Project Name]  
   - Contract Address: [Contract Address]  
   - Audit Date: [YYYY-MM-DD]  
   - Auditors: CertaiK AI Agent  

   ---

   ## 🧐 Introduction
   [Introduction Text]

   ---

   ## 🔍 Audit Scope
   [Audit Scope Text]

   ---

   ## ⚠️ Severity Levels
   - Critical: 🚨 Significant gas inefficiencies that can lead to substantial cost increases.  
   - High: 🔴 Major gas usage issues that may result in noticeable cost impacts.  
   - Medium: 🟠 Moderate gas optimization opportunities with potential cost savings.  
   - Low: 🟢 Minor gas inefficiencies with limited cost impact.  
   - Informational: 🔵 Suggestions for minor gas optimizations or best practices, with minimal cost implications.

   ---

   ## 🛠 Findings

   ### 🚨 Critical
   [Critical Findings]

   ### 🔴 High
   [High Findings]

   ### 🟠 Medium
   [Medium Findings]

   ### 🟢 Low
   [Low Findings]

   ### 🔵 Informational
   [Informational Findings]

   ---

   ## 🛡 Recommendations
   [Recommendations Text]

   ---

   ## ✅ Conclusion
   [Conclusion Text]

   ---
   \`\`\`

2. **Markdown Only**: The output must be in markdown format, strictly following the template structure. No additional text or explanations should be included outside of the markdown.

3. **Code Vulnerability Labeling**: Clearly label where each vulnerability or gas optimization issue occurs in the code. Ensure that all vulnerabilities are categorized by severity.

********************************************************************
# Code to be audited is found below:

\`\`\`

\`\`\`
`;
